<script src="<?= site_url() ?>be/assets/vendors/js/vendor.bundle.base.js"></script>
<script src="<?= site_url() ?>be/assets/vendors/chart.js/Chart.min.js"></script>
<script src="<?= site_url() ?>be/assets/vendors/progressbar.js/progressbar.min.js"></script>
<script src="<?= site_url() ?>be/assets/vendors/jvectormap/jquery-jvectormap.min.js"></script>
<script src="<?= site_url() ?>be/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="<?= site_url() ?>be/assets/vendors/owl-carousel-2/owl.carousel.min.js"></script>
<script src="<?= site_url() ?>be/assets/js/off-canvas.js"></script>
<script src="<?= site_url() ?>be/assets/js/hoverable-collapse.js"></script>
<script src="<?= site_url() ?>be/assets/js/misc.js"></script>
<script src="<?= site_url() ?>be/assets/js/settings.js"></script>
<script src="<?= site_url() ?>be/assets/js/todolist.js"></script>
<script src="<?= site_url() ?>be/assets/js/dashboard.js"></script>